"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Plan={code:string;name:string;price_monthly:number;description:string;home_feed:boolean;local_featured:boolean;video_ads:boolean;deals:boolean;coming_soon:boolean};
export default function AdvertisingPlansPage(){
 const [businessId,setBusinessId]=useState("");const [plans,setPlans]=useState<Plan[]>([]);const [pending,setPending]=useState<string|null>(null);const [message,setMessage]=useState("");const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){window.location.href="/advertise/signup";return;}const {data:b}=await s.from("businesses").select("id").eq("owner_user_id",u.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!b){window.location.href="/advertise/setup";return;}setBusinessId(b.id);const [{data:p},{data:sub}]=await Promise.all([s.from("advertising_plans").select("code,name,price_monthly,description,home_feed,local_featured,video_ads,deals,coming_soon").eq("active",true).order("price_monthly"),s.from("business_plan_subscriptions").select("plan_code,status").eq("business_id",b.id).in("status",["pending","active"]).order("created_at",{ascending:false}).limit(1).maybeSingle()]);setPlans((p??[]) as Plan[]);if(sub)setPending(sub.plan_code);})();},[]);
 async function requestPlan(code:string){setError("");setMessage("");if(code==="listed"){setMessage("Your standard Local Business listing is already available without a paid plan.");return;}const s=createClient();const {error}=await s.from("business_plan_subscriptions").insert({business_id:businessId,plan_code:code,status:"pending"});if(error){setError(error.message);return;}setPending(code);setMessage("Plan request submitted. Payment/activation will be completed before premium campaigns go live.");}
 return <main className="auth-page"><section className="auth-card wide"><Link href="/advertise/dashboard" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge sponsored">Advertising Plans</span><h1>Get noticed by residents</h1><p className="auth-copy">Choose how prominently your business should appear to verified Jordan Ranch & Tamarron residents.</p>{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}<div className="plan-grid">{plans.map(p=><article className="plan-card" key={p.code}><h3>{p.name}</h3><div className="plan-price">{Number(p.price_monthly)===0?"Free":`$${Number(p.price_monthly)}/mo`}</div><p className="plan-meta">{p.description}</p><div className="plan-meta">{p.local_featured&&"✓ Featured Local Business placement\n"}{p.home_feed&&"✓ Home feed ads\n"}{p.video_ads&&"✓ Video ads\n"}{p.deals&&"✓ Resident Deals\n"}{p.coming_soon&&"✓ Coming Soon placement"}</div><button className="btn-primary" style={{marginTop:12,width:"100%"}} disabled={pending===p.code} onClick={()=>requestPlan(p.code)}>{pending===p.code?"Requested / Active":p.code==="listed"?"Included":"Choose Plan"}</button></article>)}</div></section></main>;
}
