"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Plan={code:string;name:string;price_monthly:number;description:string;home_feed:boolean;local_featured:boolean;video_ads:boolean;deals:boolean;coming_soon:boolean};
export default function AdvertisingPlansPage(){
 const [plans,setPlans]=useState<Plan[]>([]);const [pending,setPending]=useState<string|null>(null);const [message,setMessage]=useState("");const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){window.location.href="/advertise/signup";return;}const {data:b}=await s.from("businesses").select("id,review_status").eq("owner_user_id",u.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!b){window.location.href="/advertise/setup";return;}const {data:p}=await s.from("advertising_plans").select("code,name,price_monthly,description,home_feed,local_featured,video_ads,deals,coming_soon").eq("active",true).order("price_monthly");setPlans((p??[]) as Plan[]);const params=new URLSearchParams(window.location.search);if(params.get("payment")==="canceled")setMessage("Payment was canceled. Your business application is saved and you can choose a plan when ready.");})();},[]);
 async function choosePlan(code:string){setError("");setMessage("");setPending(code);try{const r=await fetch("/api/advertise/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planCode:code})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to start payment");window.location.href=j.url;}catch(e){setError(e instanceof Error?e.message:"Unable to start payment");setPending(null);}}
 return <main className="auth-page"><section className="auth-card wide"><Link href="/advertise/dashboard" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge sponsored">Advertising Plans</span><h1>Choose how residents see your business</h1><p className="auth-copy">All plans are monthly subscriptions. Your card or eligible payment method is collected securely by Stripe; Jordan Ranch & Tamarron does not store payment-card numbers.</p>{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}<div className="plan-grid">{plans.map(p=><article className="plan-card" key={p.code}><h3>{p.name}</h3><div className="plan-price">${Number(p.price_monthly)}/mo</div><p className="plan-meta">{p.description}</p><div className="plan-meta" style={{whiteSpace:"pre-line"}}>{p.code==="listed"?"✓ Standard Local Business listing":`✓ Local Business placement${p.local_featured?"\n✓ Priority placement":""}${p.deals?"\n✓ Resident Deals":""}${p.video_ads?"\n✓ Image & video campaigns":""}${p.home_feed?"\n✓ Home feed placement":""}${p.coming_soon?"\n✓ Coming Soon placement":""}`}</div><button className="btn-primary" style={{marginTop:12,width:"100%"}} disabled={pending!==null} onClick={()=>choosePlan(p.code)}>{pending===p.code?"Opening secure checkout…":"Choose Plan & Pay"}</button></article>)}</div><div className="private-note" style={{marginTop:16}}>After payment, your business is submitted for administrative review. Paid status does not automatically guarantee approval; rejected listings will be handled under the advertising refund/cancellation policy.</div></section></main>;
}
