"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Format="image"|"video"|"carousel"|"coming_soon";
export default function NewCampaignPage(){
 const router=useRouter();const [businessId,setBusinessId]=useState("");const [format,setFormat]=useState<Format>("image");const [headline,setHeadline]=useState("");const [body,setBody]=useState("");const [file,setFile]=useState<File|null>(null);const [jr,setJr]=useState(true);const [tam,setTam]=useState(true);const [start,setStart]=useState("");const [end,setEnd]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){router.replace("/advertise/signup");return;}const {data:b}=await s.from("businesses").select("id").eq("owner_user_id",u.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!b){router.replace("/advertise/setup");return;}setBusinessId(b.id);})();},[router]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user||!businessId)return;let media:string[]=[];if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${u.user.id}/${businessId}/${Date.now()}-${safe}`;const {error:up}=await s.storage.from("business-media").upload(path,file);if(up){setError(up.message);setLoading(false);return;}const {data:url}=s.storage.from("business-media").getPublicUrl(path);media=[url.publicUrl];}
 const {error}=await s.from("business_ads").insert({business_id:businessId,format,headline:headline.trim(),body:body.trim()||null,media_urls:media,target_jordan_ranch:jr,target_tamarron:tam,starts_at:new Date(start).toISOString(),ends_at:new Date(end).toISOString(),is_active:false,approval_status:"pending"});if(error){setError(error.message);setLoading(false);return;}router.push("/advertise/dashboard");}
 return <main className="auth-page"><section className="auth-card wide"><Link href="/advertise/dashboard" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge sponsored">New Campaign</span><h1>Create an ad</h1><p className="auth-copy">Upload an image or short video. Campaigns stay in review until approved and activated.</p><form className="form-stack" onSubmit={submit}><label>Format<select value={format} onChange={e=>setFormat(e.target.value as Format)}><option value="image">Image ad</option><option value="video">Video ad</option><option value="carousel">Carousel</option><option value="coming_soon">Coming Soon</option></select></label><label>Headline<input required maxLength={100} value={headline} onChange={e=>setHeadline(e.target.value)}/></label><label>Message<textarea maxLength={500} value={body} onChange={e=>setBody(e.target.value)}/></label><label>Media<input type="file" accept={format==="video"?"video/*":"image/*"} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><div className="form-grid two"><label>Start<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="form-grid two"><label><span><input type="checkbox" checked={jr} onChange={e=>setJr(e.target.checked)}/> Jordan Ranch</span></label><label><span><input type="checkbox" checked={tam} onChange={e=>setTam(e.target.checked)}/> Tamarron</span></label></div>{error&&<div className="form-error">{error}</div>}<button className="btn-primary" disabled={loading||(!jr&&!tam)}>{loading?"Submitting…":"Submit Campaign for Review"}</button></form></section></main>;
}
