"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function EditBusinessProfile(){
 const router=useRouter();const [id,setId]=useState("");const [name,setName]=useState("");const [category,setCategory]=useState("");const [description,setDescription]=useState("");const [address,setAddress]=useState("");const [phone,setPhone]=useState("");const [website,setWebsite]=useState("");const [hours,setHours]=useState("");const [photo,setPhoto]=useState<File|null>(null);const [error,setError]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){router.replace("/advertise/signup");return;}const {data:b}=await s.from("businesses").select("id,name,category,description,address,phone,website_url,hours").eq("owner_user_id",u.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!b){router.replace("/advertise/setup");return;}setId(b.id);setName(b.name);setCategory(b.category);setDescription(b.description??"");setAddress(b.address??"");setPhone(b.phone??"");setWebsite(b.website_url??"");setHours((b.hours as {display?:string}|null)?.display??"");setLoading(false);})();},[router]);
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");setLoading(true);const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user)return;let imageUrls:string[]|undefined=undefined;if(photo){const safe=photo.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${u.user.id}/${id}/${Date.now()}-${safe}`;const {error:up}=await s.storage.from("business-media").upload(path,photo);if(up){setError(up.message);setLoading(false);return;}imageUrls=[s.storage.from("business-media").getPublicUrl(path).data.publicUrl];}const payload:any={name:name.trim(),category,description:description.trim()||null,address:address.trim()||null,phone:phone.trim()||null,website_url:website.trim()||null,hours:hours.trim()?{display:hours.trim()}:null,updated_at:new Date().toISOString()};if(imageUrls)payload.image_urls=imageUrls;const {error}=await s.from("businesses").update(payload).eq("id",id);if(error){setError(error.message);setLoading(false);return;}setMessage("Business profile updated.");setLoading(false);}
 if(loading)return <main className="auth-page"><section className="auth-card">Loading business profile…</section></main>;
 return <main className="auth-page"><section className="auth-card wide"><Link href="/advertise/dashboard" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge sponsored">Business Profile</span><h1>Edit your Local Business listing</h1><p className="auth-copy">These details appear to verified residents. Ratings, verification badges and advertising metrics cannot be edited by business owners.</p><form className="form-stack" onSubmit={submit}><label>Business name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{["Restaurants","Medical","Dental","Beauty","Home Services","Fitness","Childcare","Automotive","Shopping","Real Estate","Professional Services"].map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={1000}/></label><div className="form-grid two"><label>Address<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><label>Website<input type="url" value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://..."/></label><label>Hours<input value={hours} onChange={e=>setHours(e.target.value)} placeholder="Mon–Fri 9–5; Sat 10–3"/></label><label>Business photo<input type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label>{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}<button className="btn-primary" disabled={loading}>{loading?"Saving…":"Save Business Profile"}</button></form></section></main>;
}
