"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Ticket={id:string;category:string;subject:string;message:string;status:string;admin_reply:string|null;created_at:string;replied_at:string|null};
export default function Contact(){const [userId,setUserId]=useState("");const [accountType,setAccountType]=useState<"resident"|"business">("resident");const [tickets,setTickets]=useState<Ticket[]>([]);const [category,setCategory]=useState("general");const [subject,setSubject]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return;}setUserId(user.id);setAccountType(user.user_metadata?.account_type==="advertiser"?"business":"resident");const {data}=await s.from("support_messages").select("id,category,subject,message,status,admin_reply,created_at,replied_at").eq("user_id",user.id).order("created_at",{ascending:false});setTickets((data??[]) as Ticket[]);})();},[]);
async function submit(e:FormEvent){e.preventDefault();if(!userId)return;setBusy(true);setNotice("");const s=createClient();const {data,error}=await s.from("support_messages").insert({user_id:userId,account_type:accountType,category,subject:subject.trim(),message:message.trim()}).select("id,category,subject,message,status,admin_reply,created_at,replied_at").single();if(error)setNotice(error.message);else{setTickets(p=>[data as Ticket,...p]);setSubject("");setMessage("");setNotice("Your request was submitted. You can return here to see the status and our response.");}setBusy(false);}
return <main className="auth-page"><section className="auth-card wide"><Link href="/" className="auth-brand">Jordan Ranch & Tamarron Residents</Link><span className="badge">Contact & Support</span><h1>How can we help?</h1><p className="auth-copy">Send a private request to the JRT admin team. No separate support email account is required. Replies will appear here, and JRT may also send a transactional notification from <strong>donotreply@jrt.community</strong>.</p>
<form className="form-stack" onSubmit={submit}><label>Topic<select value={category} onChange={e=>setCategory(e.target.value)}><option value="general">General question</option><option value="account">Account help</option><option value="verification">Residency verification</option><option value="marketplace">Marketplace</option><option value="business">Business / advertising</option><option value="billing">Billing</option><option value="privacy">Privacy request</option><option value="safety">Safety / report a concern</option><option value="account_deletion">Account deletion</option></select></label><label>Subject<input required minLength={3} maxLength={160} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Briefly describe what you need"/></label><label>Message<textarea required minLength={10} maxLength={5000} rows={6} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Tell us what happened. Do not include passwords or full payment-card numbers."/></label><button className="btn-primary" disabled={busy}>{busy?"Submitting…":"Submit Request"}</button>{notice&&<div className="private-note">{notice}</div>}</form>
<section className="section"><h2>My support requests</h2>{tickets.length===0?<p className="auth-copy">You have no support requests yet.</p>:tickets.map(t=><article className="card" key={t.id}><div className="card-body"><span className="badge">{t.status.replace("_"," ")}</span><div className="card-title">{t.subject}</div><div className="card-copy">{t.message}</div><div className="meta"><span>{new Date(t.created_at).toLocaleString()}</span></div>{t.admin_reply&&<div className="private-note"><strong>JRT response:</strong><br/>{t.admin_reply}</div>}</div></article>)}</section><div className="cta-row"><Link href="/policies" className="btn-secondary" style={{textDecoration:"none",textAlign:"center"}}>Policies</Link><Link href="/" className="btn-secondary" style={{textDecoration:"none",textAlign:"center"}}>Return to JRT</Link></div></section></main>;}