"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function NewDealPage(){
 const router=useRouter();const [businessId,setBusinessId]=useState("");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [code,setCode]=useState("");const [jr,setJr]=useState(true);const [tam,setTam]=useState(true);const [start,setStart]=useState("");const [end,setEnd]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){router.replace("/advertise/signup");return;}const {data:b}=await s.from("businesses").select("id").eq("owner_user_id",u.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!b){router.replace("/advertise/setup");return;}setBusinessId(b.id);})();},[router]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const s=createClient();const {error}=await s.from("deals").insert({business_id:businessId,title:title.trim(),description:description.trim()||null,code:code.trim()||null,target_jordan_ranch:jr,target_tamarron:tam,starts_at:new Date(start).toISOString(),expires_at:new Date(end).toISOString(),is_active:false,approval_status:"pending"});if(error){setError(error.message);setLoading(false);return;}router.push("/advertise/dashboard");}
 return <main className="auth-page"><section className="auth-card wide"><Link href="/advertise/dashboard" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge">Resident Deal</span><h1>Create a resident-only offer</h1><p className="auth-copy">Deals are visible only to verified residents after approval.</p><form className="form-stack" onSubmit={submit}><label>Deal title<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="15% off dinner"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500}/></label><label>Promo code <span className="optional">optional</span><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={40}/></label><div className="form-grid two"><label>Starts<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Expires<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="form-grid two"><label><span><input type="checkbox" checked={jr} onChange={e=>setJr(e.target.checked)}/> Jordan Ranch</span></label><label><span><input type="checkbox" checked={tam} onChange={e=>setTam(e.target.checked)}/> Tamarron</span></label></div>{error&&<div className="form-error">{error}</div>}<button className="btn-primary" disabled={loading||(!jr&&!tam)}>{loading?"Submitting…":"Submit Deal for Review"}</button></form></section></main>;
}
