"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function EditProfilePage(){
 const router=useRouter();const [first,setFirst]=useState("");const [last,setLast]=useState("");const [profession,setProfession]=useState("");const [business,setBusiness]=useState("");const [photo,setPhoto]=useState<File|null>(null);const [currentPhoto,setCurrentPhoto]=useState<string|null>(null);const [community,setCommunity]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){router.replace("/login");return;}const {data:p}=await s.from("profiles").select("first_name,last_initial,profession,business_name,profile_photo_url,community").eq("id",u.user.id).maybeSingle();if(!p){router.replace("/verify-residency");return;}setFirst(p.first_name);setLast(p.last_initial);setProfession(p.profession??"");setBusiness(p.business_name??"");setCurrentPhoto(p.profile_photo_url);setCommunity(p.community==="jordan_ranch"?"Jordan Ranch":"Tamarron");setLoading(false);})();},[router]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user)return;let photoUrl=currentPhoto;if(photo){const safe=photo.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${u.user.id}/${Date.now()}-${safe}`;const {error:up}=await s.storage.from("resident-avatars").upload(path,photo,{upsert:false});if(up){setError(up.message);setLoading(false);return;}photoUrl=s.storage.from("resident-avatars").getPublicUrl(path).data.publicUrl;}const {error}=await s.from("profiles").update({first_name:first.trim(),last_initial:last.trim().slice(0,1).toUpperCase(),profession:profession.trim()||null,business_name:business.trim()||null,profile_photo_url:photoUrl,updated_at:new Date().toISOString()}).eq("id",u.user.id);if(error){setError(error.message);setLoading(false);return;}router.push("/");router.refresh();}
 if(loading)return <main className="auth-page"><section className="auth-card">Loading profile…</section></main>;
 return <main className="auth-page"><section className="auth-card wide"><Link href="/" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge">Resident Profile</span><h1>Edit profile</h1><p className="auth-copy">Your public profile stays intentionally simple. No bio, website, address, email or phone number is displayed.</p><form className="form-stack" onSubmit={submit}><div className="form-grid two"><label>First name<input required value={first} onChange={e=>setFirst(e.target.value)} maxLength={50}/></label><label>Last initial<input required value={last} onChange={e=>setLast(e.target.value.replace(/[^a-zA-Z]/g,"").slice(0,1))} maxLength={1}/></label></div><label>Profile photo<input type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label><div className="form-grid two"><label>Profession <span className="optional">optional</span><input value={profession} onChange={e=>setProfession(e.target.value)} maxLength={80}/></label><label>Business <span className="optional">optional</span><input value={business} onChange={e=>setBusiness(e.target.value)} maxLength={100}/></label></div><div className="private-note"><strong>Verified community:</strong> {community}. Community changes require residency verification and cannot be changed here.</div>{error&&<div className="form-error">{error}</div>}<button className="btn-primary" disabled={loading}>{loading?"Saving…":"Save Profile"}</button></form></section></main>;
}
