"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Community="jordan_ranch"|"tamarron";
export default function NewListingPage(){
 const router=useRouter();const [community,setCommunity]=useState<Community>("jordan_ranch");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [price,setPrice]=useState("");const [category,setCategory]=useState("Furniture");const [both,setBoth]=useState(true);const [files,setFiles]=useState<File[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){router.replace("/login");return;}const {data:p}=await s.from("profiles").select("community,verification_status").eq("id",u.user.id).maybeSingle();if(!p||p.verification_status!=="verified"){router.replace("/verify-residency");return;}setCommunity(p.community as Community);})();},[router]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user)return;const urls:string[]=[];for(const file of files.slice(0,5)){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${u.user.id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;const {error:up}=await s.storage.from("marketplace-media").upload(path,file);if(up){setError(up.message);setLoading(false);return;}const {data:url}=s.storage.from("marketplace-media").getPublicUrl(path);urls.push(url.publicUrl);}const numericPrice=price.trim()===""?null:Number(price);const {error}=await s.from("marketplace_listings").insert({seller_id:u.user.id,title:title.trim(),description:description.trim()||null,price:numericPrice,category,community,visible_to_both:both,image_urls:urls,status:"active"});if(error){setError(error.message);setLoading(false);return;}router.push("/");router.refresh();}
 return <main className="auth-page"><section className="auth-card wide"><Link href="/" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge">Resident Marketplace</span><h1>Sell something</h1><p className="auth-copy">Listings are available only to verified residents. Your street address is never shown.</p><form className="form-stack" onSubmit={submit}><label>Title<input required maxLength={100} value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="form-grid two"><label>Price <span className="optional">leave blank for Free</span><input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{["Furniture","Kids & Baby","Electronics","Home & Garden","Appliances","Clothing","Tools","Vehicles","Free Stuff","Other"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={1000}/></label><label>Photos <span className="optional">up to 5</span><input type="file" multiple accept="image/*" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,5))}/></label><label><span><input type="checkbox" checked={both} onChange={e=>setBoth(e.target.checked)}/> Show this listing to verified residents in both Jordan Ranch and Tamarron</span></label><div className="private-note">Posting as a verified {community==="jordan_ranch"?"Jordan Ranch":"Tamarron"} resident.</div>{error&&<div className="form-error">{error}</div>}<button className="btn-primary" disabled={loading}>{loading?"Publishing…":"Publish Listing"}</button></form></section></main>;
}
