"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Home, Store, Tags, User, ShoppingBag, CalendarDays, Building2, PlusCircle, Eye, MapPin, ShieldCheck, Play, Bookmark, LogOut, BadgePercent } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Tab="home"|"marketplace"|"business"|"deals"|"profile";
type Profile={id:string;first_name:string;last_initial:string;profile_photo_url:string|null;community:"jordan_ranch"|"tamarron";profession:string|null;business_name:string|null;member_since:string};
type Listing={id:string;title:string;price:number|null;community:"jordan_ranch"|"tamarron";view_count:number;image_urls:string[];category:string;created_at:string};
type Business={id:string;name:string;category:string;description:string|null;average_rating:number;rating_count:number;profile_view_count:number;logo_url:string|null;image_urls:string[]};
type Ad={id:string;headline:string;body:string|null;format:string;media_urls:string[];impression_count:number;video_play_count:number;click_count:number;businesses:{id:string;name:string}|null};
type Deal={id:string;title:string;description:string|null;code:string|null;view_count:number;claim_count:number;expires_at:string;businesses:{id:string;name:string}|null};
type Props={profile:Profile;residentCount:{total:number;jordan:number;tamarron:number};listings:Listing[];businesses:Business[];ads:Ad[];deals:Deal[]};

const communityLabel=(c:string)=>c==="jordan_ranch"?"Jordan Ranch":"Tamarron";

export default function ResidentApp({profile,residentCount,listings,businesses,ads,deals}:Props){
 const [tab,setTab]=useState<Tab>("home");const [saved,setSaved]=useState<Set<string>>(new Set());const [claimed,setClaimed]=useState<Set<string>>(new Set());const router=useRouter();
 const comingSoon=useMemo(()=>ads.filter(a=>a.format==="coming_soon"),[ads]);

 useEffect(()=>{const s=createClient();ads.forEach(a=>{void s.rpc("record_ad_event",{p_ad_id:a.id,p_event:"impression"});});},[ads]);
 useEffect(()=>{if(tab!=="deals")return;const s=createClient();deals.forEach(d=>{void s.rpc("record_deal_view",{p_deal_id:d.id});});},[tab,deals]);

 async function toggleSave(kind:"marketplace"|"business"|"deal",id:string){const s=createClient();const key=`${kind}:${id}`;const table=kind==="marketplace"?"saved_marketplace":kind==="business"?"saved_businesses":"saved_deals";const column=kind==="marketplace"?"listing_id":kind==="business"?"business_id":"deal_id";if(saved.has(key)){await s.from(table).delete().eq("user_id",profile.id).eq(column,id);setSaved(prev=>{const n=new Set(prev);n.delete(key);return n;});}else{await s.from(table).insert({user_id:profile.id,[column]:id});setSaved(prev=>new Set(prev).add(key));}}
 async function claimDeal(id:string){const s=createClient();const {error}=await s.from("deal_claims").insert({deal_id:id,user_id:profile.id});if(!error)setClaimed(prev=>new Set(prev).add(id));}
 async function adEvent(adId:string,event:"video_play"|"click"){const s=createClient();await s.rpc("record_ad_event",{p_ad_id:adId,p_event:event});}
 async function signOut(){const s=createClient();await s.auth.signOut();router.replace("/login");router.refresh();}
 function openAdBusiness(a:Ad){void adEvent(a.id,"click");if(a.businesses?.id)router.push(`/business/${a.businesses.id}`);}

 const AdCard=({a}:{a:Ad})=><article className="card">{a.media_urls[0]?(a.format==="video"?<video className="ad-video" src={a.media_urls[0]} autoPlay muted loop playsInline onPlay={()=>void adEvent(a.id,"video_play")}/>:<div className="media-placeholder" style={{backgroundImage:`url(${a.media_urls[0]})`,backgroundSize:"cover",backgroundPosition:"center"}}/>):<div className="media-placeholder">{a.format==="video"&&<Play size={34}/>} Sponsored media</div>}<div className="card-body"><span className="badge sponsored">Sponsored</span><div className="card-title">{a.headline}</div>{a.body&&<div className="card-copy">{a.body}</div>}<div className="meta"><span>{a.businesses?.name}</span><span><Eye size={12}/> {a.impression_count} views</span>{a.format==="video"&&<span>{a.video_play_count} video plays</span>}</div>{a.businesses?.id&&<div className="cta-row"><button className="btn-primary" onClick={()=>openAdBusiness(a)}>View Business</button></div>}</div></article>;

 return <div className="app-shell">
  <header className="topbar"><div className="brand-row"><div className="brand">Jordan Ranch & Tamarron</div><button className="community-pill">{communityLabel(profile.community)}</button></div><div className="counter-card"><div className="counter-main">{residentCount.total.toLocaleString()} Verified Residents</div><div className="counter-sub">Jordan Ranch {residentCount.jordan.toLocaleString()} · Tamarron {residentCount.tamarron.toLocaleString()}</div></div></header>

  {tab==="home"&&<main className="content"><section className="section"><div className="quick-grid"><button className="quick-card"><Building2 size={21}/><span className="quick-label">Coming Soon</span></button><button className="quick-card"><CalendarDays size={21}/><span className="quick-label">Events</span></button><button className="quick-card" onClick={()=>router.push("/marketplace/new")}><PlusCircle size={21}/><span className="quick-label">Sell Item</span></button><button className="quick-card" onClick={()=>setTab("business")}><Store size={21}/><span className="quick-label">Find Business</span></button></div></section>
   <section className="section"><div className="section-head"><div className="section-title">Around the Communities</div></div><article className="card"><div className="card-body"><div className="eyebrow">Community Update</div><div className="card-title">Welcome to the private Jordan Ranch & Tamarron resident network</div><div className="card-copy">Marketplace, local businesses, resident-only deals and neighborhood information without comments or likes.</div></div></article>
    {listings.slice(0,2).map(l=><article className="card" key={l.id} onClick={()=>router.push(`/marketplace/${l.id}`)}>{l.image_urls[0]?<div className="media-placeholder" style={{backgroundImage:`url(${l.image_urls[0]})`,backgroundSize:"cover",backgroundPosition:"center"}}/>:<div className="media-placeholder">Marketplace photo</div>}<div className="card-body"><span className="badge">Marketplace</span><div className="card-title">{l.title}{l.price!==null?` · $${Number(l.price).toLocaleString()}`:""}</div><div className="meta"><span><MapPin size={12}/> {communityLabel(l.community)}</span><span><Eye size={12}/> {l.view_count} views</span></div></div></article>)}
    {ads.slice(0,2).map(a=><AdCard a={a} key={a.id}/>)}
    {comingSoon.slice(0,2).map(a=><article className="card" key={`soon-${a.id}`}><div className="card-body"><div className="eyebrow">Coming Soon</div><div className="card-title">{a.headline}</div>{a.body&&<div className="card-copy">{a.body}</div>}</div></article>)}
   </section></main>}

  {tab==="marketplace"&&<main className="content"><input className="search" placeholder="Search Marketplace"/><div className="section-head" style={{marginTop:14}}><div className="section-title">Resident Marketplace</div><button className="section-link" onClick={()=>router.push("/marketplace/new")}>+ Create listing</button></div>{listings.length===0?<article className="card"><div className="card-body"><div className="card-title">No listings yet</div><div className="card-copy">Be one of the first verified residents to list an item.</div></div></article>:listings.map(l=><article className="card" key={l.id}>{l.image_urls[0]?<div className="media-placeholder" style={{backgroundImage:`url(${l.image_urls[0]})`,backgroundSize:"cover",backgroundPosition:"center"}}/>:<div className="media-placeholder">Listing photo</div>}<div className="card-body"><div className="card-title">{l.title}{l.price!==null?` · $${Number(l.price).toLocaleString()}`:""}</div><div className="meta"><span><ShieldCheck size={12}/> Verified resident</span><span>{communityLabel(l.community)}</span><span><Eye size={12}/> {l.view_count} views</span></div><div className="cta-row"><button className="btn-primary" onClick={()=>router.push(`/marketplace/${l.id}`)}>View Listing</button><button className="btn-secondary" onClick={()=>toggleSave("marketplace",l.id)}><Bookmark size={16}/></button></div></div></article>)}</main>}

  {tab==="business"&&<main className="content"><input className="search" placeholder="What local business are you looking for?"/><section className="business-cta"><h3>Own a local business?</h3><p>Get noticed by verified Jordan Ranch & Tamarron residents with image ads, video ads, resident deals and featured placement.</p><button className="btn-primary" onClick={()=>router.push("/advertise")}>Advertise Your Business</button></section>{ads.length>0&&<><div className="section-head"><div className="section-title">Sponsored Businesses</div></div>{ads.slice(0,3).map(a=><AdCard a={a} key={`local-${a.id}`}/>)}</>}<div className="section-head"><div className="section-title">Local Businesses</div></div>{businesses.length===0?<article className="card"><div className="card-body"><div className="card-title">Business directory is opening soon</div></div></article>:businesses.map(b=><article className="card" key={b.id}><div className="card-body"><div className="card-title">{b.name}</div><div className="card-copy">{b.category}{b.description?` · ${b.description}`:""}</div><div className="meta"><span>{Number(b.average_rating).toFixed(1)} ★ · {b.rating_count} ratings</span><span><Eye size={12}/> {b.profile_view_count} profile views</span></div><div className="cta-row"><button className="btn-primary" onClick={()=>router.push(`/business/${b.id}`)}>View Business</button><button className="btn-secondary" onClick={()=>toggleSave("business",b.id)}><Bookmark size={16}/></button></div></div></article>)}</main>}

  {tab==="deals"&&<main className="content"><div className="section-head"><div className="section-title">Resident-Only Deals</div><span className="section-link">Verified access</span></div>{deals.length===0?<article className="card"><div className="card-body"><div className="card-title">No active deals yet</div><div className="card-copy">Local business offers will appear here after approval.</div></div></article>:deals.map(d=><article className="card" key={d.id}><div className="card-body"><span className="badge"><BadgePercent size={13}/> Resident Deal</span><div className="card-title">{d.title} · {d.businesses?.name}</div>{d.description&&<div className="card-copy">{d.description}</div>}<div className="meta"><span><Eye size={12}/> {d.view_count} views</span><span>{d.claim_count} claims</span><span>Expires {new Date(d.expires_at).toLocaleDateString()}</span></div><div className="cta-row"><button className="btn-primary" onClick={()=>claimDeal(d.id)} disabled={claimed.has(d.id)}>{claimed.has(d.id)?"Claimed":"Claim Deal"}</button><button className="btn-secondary" onClick={()=>toggleSave("deal",d.id)}>Save</button></div></div></article>)}</main>}

  {tab==="profile"&&<main className="content"><section className="card profile-card">{profile.profile_photo_url?<img className="avatar-photo" src={profile.profile_photo_url} alt="Profile"/>:<div className="avatar">{profile.first_name[0]}{profile.last_initial}</div>}<div className="profile-name">{profile.first_name} {profile.last_initial}.</div><div className="profile-detail">✓ Verified {communityLabel(profile.community)} Resident</div>{profile.profession&&<div className="profile-detail">Profession: {profile.profession}</div>}{profile.business_name&&<div className="profile-detail">Business: {profile.business_name}</div>}<div className="profile-detail">Member since {new Date(profile.member_since).toLocaleDateString(undefined,{month:"long",year:"numeric"})}</div><div className="private-note"><strong>Privacy:</strong> Your residential address is used for verification only and is never displayed to other residents.</div></section><section className="section"><div className="section-title" style={{marginBottom:10}}>My Private Content</div><button className="card profile-link" onClick={()=>router.push("/profile/saved")}>Saved Content</button><button className="card profile-link" onClick={()=>router.push("/profile/listings")}>My Marketplace Listings</button><button className="card profile-link" onClick={()=>router.push("/profile/edit")}>Edit Profile</button><button className="card profile-link" onClick={()=>router.push("/verify-residency")}>Account & Verification</button><button className="btn-secondary" style={{width:"100%"}} onClick={signOut}><LogOut size={16}/> Sign out</button></section></main>}

  <nav className="bottom-nav"><button className={`nav-btn ${tab==="home"?"active":""}`} onClick={()=>setTab("home")}><Home size={20}/>Home</button><button className={`nav-btn ${tab==="marketplace"?"active":""}`} onClick={()=>setTab("marketplace")}><ShoppingBag size={20}/>Marketplace</button><button className={`nav-btn ${tab==="business"?"active":""}`} onClick={()=>setTab("business")}><Store size={20}/>Local Business</button><button className={`nav-btn ${tab==="deals"?"active":""}`} onClick={()=>setTab("deals")}><Tags size={20}/>Deals</button><button className={`nav-btn ${tab==="profile"?"active":""}`} onClick={()=>setTab("profile")}><User size={20}/>Profile</button></nav>
 </div>;
}
