"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Business={id:string;name:string;legal_business_name:string|null;category:string;description:string|null;contact_first_name:string|null;contact_last_name:string|null;contact_email:string|null;business_email:string|null;phone:string|null;address_line1:string|null;city:string|null;state:string|null;postal_code:string|null;website_url:string|null;license_type:string|null;license_number:string|null;review_status:string;current_plan_code:string|null;created_at:string};
type PlanRequest={id:string;business_id:string;plan_code:string;status:string;payment_status:string;created_at:string;businesses:{name:string}|null;advertising_plans:{name:string;price_monthly:number}|null};
type Ad={id:string;headline:string;format:string;placement_home:boolean;placement_local:boolean;approval_status:string;businesses:{name:string}|null};
type Deal={id:string;title:string;approval_status:string;businesses:{name:string}|null};

export default function AdvertisingAdminPage(){
 const [authorized,setAuthorized]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [businesses,setBusinesses]=useState<Business[]>([]);const [plans,setPlans]=useState<PlanRequest[]>([]);const [ads,setAds]=useState<Ad[]>([]);const [deals,setDeals]=useState<Deal[]>([]);
 async function load(){const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){window.location.href="/login";return;}const {data:admin}=await s.from("app_admins").select("user_id").eq("user_id",u.user.id).maybeSingle();if(!admin){setLoading(false);return;}setAuthorized(true);const[b,p,a,d]=await Promise.all([s.from("businesses").select("id,name,legal_business_name,category,description,contact_first_name,contact_last_name,contact_email,business_email,phone,address_line1,city,state,postal_code,website_url,license_type,license_number,review_status,current_plan_code,created_at").eq("review_status","submitted").order("submitted_at",{ascending:true}),s.from("business_plan_subscriptions").select("id,business_id,plan_code,status,payment_status,created_at,businesses(name),advertising_plans(name,price_monthly)").in("status",["pending","active"]).order("created_at",{ascending:true}),s.from("business_ads").select("id,headline,format,placement_home,placement_local,approval_status,businesses(name)").eq("approval_status","pending").order("created_at",{ascending:true}),s.from("deals").select("id,title,approval_status,businesses(name)").eq("approval_status","pending").order("created_at",{ascending:true})]);if(b.error||p.error||a.error||d.error)setError(b.error?.message||p.error?.message||a.error?.message||d.error?.message||"Unable to load review queue");setBusinesses((b.data??[]) as Business[]);setPlans((p.data??[]) as unknown as PlanRequest[]);setAds((a.data??[]) as unknown as Ad[]);setDeals((d.data??[]) as unknown as Deal[]);setLoading(false);}
 useEffect(()=>{void load();},[]);
 async function reviewBusiness(id:string,approved:boolean){const s=createClient();setError("");if(approved){const {data:paid}=await s.from("business_plan_subscriptions").select("id").eq("business_id",id).eq("status","active").eq("payment_status","paid").limit(1).maybeSingle();if(!paid){setError("This business cannot be approved until its paid subscription is active.");return;}}const {error:e}=await s.from("businesses").update({is_verified:approved,review_status:approved?"approved":"rejected",reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);if(e){setError(e.message);return;}setBusinesses(x=>x.filter(b=>b.id!==id));}
 async function reviewAd(id:string,approved:boolean){const s=createClient();const {error:e}=await s.from("business_ads").update({approval_status:approved?"approved":"rejected",is_active:approved}).eq("id",id);if(e){setError(e.message);return;}setAds(x=>x.filter(a=>a.id!==id));}
 async function reviewDeal(id:string,approved:boolean){const s=createClient();const {error:e}=await s.from("deals").update({approval_status:approved?"approved":"rejected",is_active:approved}).eq("id",id);if(e){setError(e.message);return;}setDeals(x=>x.filter(d=>d.id!==id));}
 if(loading)return <main className="auth-page"><section className="auth-card">Loading advertising approvals…</section></main>;if(!authorized)return <main className="auth-page"><section className="auth-card"><h1>Admin access required</h1><Link href="/" className="btn-secondary">Return Home</Link></section></main>;
 return <main className="auth-page"><section className="auth-card wide"><Link href="/" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge">Admin</span><h1>Business & advertising review</h1><p className="auth-copy">Paid business applications must be approved before residents can see them. Campaign and Deal entitlements are also enforced by the database.</p>{error&&<div className="form-error">{error}</div>}
 <section className="section"><div className="section-title">Business Applications</div>{businesses.length===0?<p className="auth-copy">No businesses awaiting review.</p>:businesses.map(b=><article className="card" key={b.id}><div className="card-body"><div className="card-title">{b.name} · {b.current_plan_code??"plan pending"}</div><div className="card-copy">{b.legal_business_name} · {b.category}<br/>{b.description}<br/>{b.address_line1}, {b.city}, {b.state} {b.postal_code}<br/>Contact: {b.contact_first_name} {b.contact_last_name} · {b.contact_email} · {b.phone}{b.website_url?<><br/>{b.website_url}</>:null}{b.license_type?<><br/>Credential: {b.license_type} {b.license_number}</>:null}</div><div className="cta-row"><button className="btn-primary" onClick={()=>reviewBusiness(b.id,true)}>Approve Business</button><button className="btn-secondary" onClick={()=>reviewBusiness(b.id,false)}>Reject</button></div></div></article>)}</section>
 <section className="section"><div className="section-title">Billing / Subscription Status</div>{plans.length===0?<p className="auth-copy">No active or processing subscriptions.</p>:plans.map(p=><article className="card" key={p.id}><div className="card-body"><div className="card-title">{p.businesses?.name} · {p.advertising_plans?.name??p.plan_code}</div><div className="meta"><span>${Number(p.advertising_plans?.price_monthly??0)}/mo</span><span>Subscription: {p.status}</span><span>Payment: {p.payment_status}</span></div></div></article>)}</section>
 <section className="section"><div className="section-title">Ad Campaigns</div>{ads.length===0?<p className="auth-copy">No pending campaigns.</p>:ads.map(a=><article className="card" key={a.id}><div className="card-body"><div className="card-title">{a.headline}</div><div className="meta"><span>{a.businesses?.name}</span><span>{a.format}</span><span>{a.placement_home?"Home ":""}{a.placement_local?"Local":""}</span></div><div className="cta-row"><button className="btn-primary" onClick={()=>reviewAd(a.id,true)}>Approve</button><button className="btn-secondary" onClick={()=>reviewAd(a.id,false)}>Reject</button></div></div></article>)}</section>
 <section className="section"><div className="section-title">Resident Deals</div>{deals.length===0?<p className="auth-copy">No pending deals.</p>:deals.map(d=><article className="card" key={d.id}><div className="card-body"><div className="card-title">{d.title} · {d.businesses?.name}</div><div className="cta-row"><button className="btn-primary" onClick={()=>reviewDeal(d.id,true)}>Approve</button><button className="btn-secondary" onClick={()=>reviewDeal(d.id,false)}>Reject</button></div></div></article>)}</section>
 </section></main>;
}
