"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Verification={id:string;user_id:string;community:"jordan_ranch"|"tamarron";residential_address:string;evidence_path:string|null;status:string;created_at:string};
type Profile={id:string;first_name:string;last_initial:string;profession:string|null;business_name:string|null};

export default function VerificationAdminPage(){
 const [rows,setRows]=useState<Array<Verification&{profile?:Profile}>>([]);const [loading,setLoading]=useState(true);const [authorized,setAuthorized]=useState(false);const [error,setError]=useState("");
 async function load(){const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){window.location.href="/login";return;}const {data:admin}=await s.from("app_admins").select("user_id").eq("user_id",u.user.id).maybeSingle();if(!admin){setLoading(false);setAuthorized(false);return;}setAuthorized(true);const {data:v,error}=await s.from("resident_verifications").select("id,user_id,community,residential_address,evidence_path,status,created_at").eq("status","pending").order("created_at",{ascending:true});if(error){setError(error.message);setLoading(false);return;}const ids=(v??[]).map(x=>x.user_id);const {data:p}=ids.length?await s.from("profiles").select("id,first_name,last_initial,profession,business_name").in("id",ids):{data:[] as Profile[]};const map=new Map((p??[]).map(x=>[x.id,x]));setRows((v??[]).map(x=>({...x,profile:map.get(x.user_id)})));setLoading(false);}
 useEffect(()=>{load();},[]);
 async function review(row:Verification,status:"verified"|"rejected"){const s=createClient();setError("");const {error:e1}=await s.from("resident_verifications").update({status,reviewed_at:new Date().toISOString()}).eq("id",row.id);if(e1){setError(e1.message);return;}const {error:e2}=await s.from("profiles").update({verification_status:status}).eq("id",row.user_id);if(e2){setError(e2.message);return;}setRows(prev=>prev.filter(x=>x.id!==row.id));}
 async function proof(path:string){const s=createClient();const {data,error}=await s.storage.from("verification-documents").createSignedUrl(path,300);if(error){setError(error.message);return;}window.open(data.signedUrl,"_blank","noopener,noreferrer");}
 if(loading)return <main className="auth-page"><section className="auth-card">Loading verification queue…</section></main>;
 if(!authorized)return <main className="auth-page"><section className="auth-card"><h1>Admin access required</h1><p className="auth-copy">This area is restricted to platform administrators.</p><Link href="/" className="btn-secondary" style={{textDecoration:"none"}}>Return Home</Link></section></main>;
 return <main className="auth-page"><section className="auth-card wide"><Link href="/" className="auth-brand">Jordan Ranch & Tamarron</Link><span className="badge">Admin</span><h1>Resident verification queue</h1><p className="auth-copy">Addresses and proof documents shown here are private verification data and never appear on resident profiles.</p>{error&&<div className="form-error">{error}</div>}{rows.length===0?<div className="form-success">No pending resident verifications.</div>:<div style={{overflowX:"auto"}}><table className="admin-table"><thead><tr><th>Resident</th><th>Community</th><th>Address</th><th>Proof</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.profile?`${r.profile.first_name} ${r.profile.last_initial}.`:"Resident"}</td><td>{r.community==="jordan_ranch"?"Jordan Ranch":"Tamarron"}</td><td>{r.residential_address}</td><td>{r.evidence_path?<button className="btn-secondary" onClick={()=>proof(r.evidence_path!)}>View proof</button>:"Not provided"}</td><td><div className="admin-actions"><button className="btn-primary" onClick={()=>review(r,"verified")}>Approve</button><button className="btn-secondary" onClick={()=>review(r,"rejected")}>Reject</button></div></td></tr>)}</tbody></table></div>}</section></main>;
}
