"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Ticket={id:string;account_type:string;category:string;subject:string;message:string;status:string;admin_reply:string|null;created_at:string};
export default function AdminSupport(){const [authorized,setAuthorized]=useState<boolean|null>(null);const [tickets,setTickets]=useState<Ticket[]>([]);const [replies,setReplies]=useState<Record<string,string>>({});const [notice,setNotice]=useState("");
async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return;}const {data:a}=await s.from("app_admins").select("user_id").eq("user_id",user.id).maybeSingle();if(!a){setAuthorized(false);return;}setAuthorized(true);const {data}=await s.from("support_messages").select("id,account_type,category,subject,message,status,admin_reply,created_at").order("created_at",{ascending:false});setTickets((data??[]) as Ticket[]);}useEffect(()=>{void load();},[]);
async function reply(t:Ticket){const text=(replies[t.id]??"").trim();if(!text)return;setNotice("Sending response…");const r=await fetch("/api/support/reply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:t.id,reply:text,status:"resolved"})});const j=await r.json();if(!r.ok){setNotice(j.error??"Could not send response");return;}setNotice(j.emailed?"Response saved and email notification sent.":"Response saved in JRT. Email was not sent; check RESEND_API_KEY if email notification is desired.");setReplies(p=>({...p,[t.id]:""}));await load();}
if(authorized===null)return <main className="auth-page"><section className="auth-card">Loading support inbox…</section></main>;if(!authorized)return <main className="auth-page"><section className="auth-card"><h1>Admin access required</h1><Link href="/" className="btn-secondary">Return Home</Link></section></main>;
return <main className="auth-page"><section className="auth-card wide"><Link href="/admin" className="auth-brand">JRT Admin Center</Link><span className="badge">Support Inbox</span><h1>Resident & business support</h1><p className="auth-copy">Review requests here. Replies are stored in the user's JRT support history and, when Resend is configured, also sent from donotreply@jrt.community.</p>{notice&&<div className="private-note">{notice}</div>}{tickets.length===0?<p>No support requests.</p>:tickets.map(t=><article className="card" key={t.id}><div className="card-body"><div className="meta"><span className="badge">{t.status.replace("_"," ")}</span><span>{t.account_type}</span><span>{t.category.replace("_"," ")}</span><span>{new Date(t.created_at).toLocaleString()}</span></div><div className="card-title">{t.subject}</div><div className="card-copy">{t.message}</div>{t.admin_reply&&<div className="private-note"><strong>Current response:</strong><br/>{t.admin_reply}</div>}<textarea rows={4} value={replies[t.id]??""} onChange={e=>setReplies(p=>({...p,[t.id]:e.target.value}))} placeholder="Write a response…"/><button className="btn-primary" onClick={()=>void reply(t)}>Send Response & Resolve</button></div></article>)}</section></main>;}