"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Business={id:string;name:string;category:string;profile_view_count:number;is_verified:boolean;promotion_rank:number|null;review_status?:string};
type Deal={id:string;title:string;view_count:number;claim_count:number;is_active:boolean;approval_status:string};
type LeaderboardStatus={businessName:string;category:string;currentBid:number;rank:number|null;nextBid:number;activeSubscription:boolean};

export default function AdvertiserDashboard(){
 const [business,setBusiness]=useState<Business|null>(null);const [deals,setDeals]=useState<Deal[]>([]);const [leaderboard,setLeaderboard]=useState<LeaderboardStatus|null>(null);const [loading,setLoading]=useState(true);const [canManageBilling,setCanManageBilling]=useState(false);const [billingLoading,setBillingLoading]=useState(false);const [billingError,setBillingError]=useState("");
 useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){window.location.href="/advertise/signup";return;}const {data:b}=await s.from("businesses").select("id,name,category,profile_view_count,is_verified,promotion_rank,review_status").eq("owner_user_id",u.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!b){window.location.href="/advertise/setup";return;}setBusiness(b);const [{data:d},{data:sub},statusResponse]=await Promise.all([s.from("deals").select("id,title,view_count,claim_count,is_active,approval_status").eq("business_id",b.id).order("created_at",{ascending:false}),s.from("business_plan_subscriptions").select("status,stripe_customer_id,stripe_subscription_id").eq("business_id",b.id).in("status",["pending","active","past_due"]).order("created_at",{ascending:false}).limit(1).maybeSingle(),fetch("/api/advertise/leaderboard",{cache:"no-store"})]);setDeals((d??[]) as Deal[]);setCanManageBilling(Boolean(sub?.stripe_customer_id));if(statusResponse.ok)setLeaderboard(await statusResponse.json());setLoading(false);})();},[]);
 async function manageSubscription(){if(billingLoading)return;setBillingLoading(true);setBillingError("");try{const response=await fetch("/api/advertise/portal",{method:"POST"});const data=await response.json();if(!response.ok||!data?.url)throw new Error(data?.error||"Unable to open billing management.");window.location.href=data.url;}catch(error){setBillingError(error instanceof Error?error.message:"Unable to open billing management.");setBillingLoading(false);}}
 if(loading)return <main className="auth-page"><section className="auth-card">Loading business dashboard…</section></main>;
 if(!business)return null;
 return <main className="auth-page"><section className="auth-card wide">
  <Link href="/advertise" className="auth-brand">JRT.Community</Link><span className="badge sponsored">Business Dashboard</span>
  <h1>{business.name}</h1><p className="auth-copy">{business.category} · {business.is_verified?"Approved business":"Business review pending"} · {business.profile_view_count} profile views</p>
  <div className="cta-row"><Link className="btn-secondary" href="/advertise/profile" style={{textDecoration:"none",textAlign:"center"}}>Edit Business Profile</Link><Link className="btn-secondary" href={`/business/${business.id}`} style={{textDecoration:"none",textAlign:"center"}}>Preview Resident View</Link></div>
  <article className="card" style={{marginTop:14}}><div className="card-body"><div className="eyebrow">Free Business Listing</div><div className="card-title">Your directory listing does not require a paid plan.</div><p className="auth-copy" style={{marginBottom:0}}>Once approved, residents can discover your business organically. Payment is only required if you choose to compete for sponsored leaderboard placement.</p></div></article>
  <article className="card" style={{marginTop:14}}><div className="card-body"><div className="eyebrow">Sponsored Leaderboard</div><div className="card-title">{leaderboard?.rank?`Rank #${leaderboard.rank} · $${leaderboard.currentBid}/mo`:"Not currently sponsored"}</div><p className="auth-copy">{leaderboard?.rank?`Your active monthly visibility bid places you #${leaderboard.rank} in ${business.category}.`:leaderboard?`Start at $${leaderboard.nextBid}/mo or choose a higher amount to compete for visibility in ${business.category}.`:"Choose your own monthly visibility bid to compete for a higher position in your category."}</p><div className="cta-row"><Link className="btn-primary" href="/advertise/plans" style={{textAlign:"center",textDecoration:"none"}}>{leaderboard?.rank?"View Leaderboard Bid":"Boost Your Rank"}</Link>{canManageBilling&&<button className="btn-secondary" onClick={manageSubscription} disabled={billingLoading}>{billingLoading?"Opening Billing…":"Manage Billing"}</button>}</div>{billingError&&<div className="form-error" style={{marginTop:10}}>{billingError}</div>}{canManageBilling&&<p className="auth-copy" style={{marginTop:10,marginBottom:0}}>Manage payment method, invoices and cancellation securely through Stripe. After cancellation becomes effective, you can start a new visibility bid.</p>}</div></article>
  <div className="cta-row"><Link className="btn-secondary" href="/advertise/deal/new" style={{textDecoration:"none",textAlign:"center"}}>Create Resident Deal</Link></div>
  <div className="section"><div className="section-title">Resident Deals</div>{deals.length===0?<p className="auth-copy">No resident deals yet. Approved businesses can create offers for residents without buying a fixed advertising tier.</p>:deals.map(d=><article className="card" key={d.id}><div className="card-body"><span className="badge">{d.approval_status==="approved"&&d.is_active?"Active":d.approval_status==="pending"?"Pending Review":d.approval_status}</span><div className="card-title">{d.title}</div><div className="meta"><span>{d.view_count} views</span><span>{d.claim_count} claims</span></div></div></article>)}</div>
 </section></main>;
}
